CREATE TABLE `sys_log` (
  `ID` int(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USERNAME` varchar(50) DEFAULT NULL COMMENT '用户名',
  `OPERATION` varchar(50) DEFAULT NULL COMMENT '用户操作',
  `TIME` int(11) DEFAULT NULL COMMENT '响应时间',
  `METHOD` varchar(200) DEFAULT NULL COMMENT '请求方法',
  `PARAMS` varchar(500) DEFAULT NULL COMMENT '请求参数',
  `IP` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;